language: python
python:
- '3.6'
install:
- pip install ansible==2.3.0 molecule apache-libcloud
env:
  matrix:
  - GCE_CREDENTIALS_FILE="$(pwd)/credentials.json"
  global:
  - secure: IG3eqygoRxyZHS7IWqVk58TvZXSusO3grBdbODOS0vykA36ghwANq/Zfym0kRUX6eV+Z2/pp/cfOQGtS27oVV9DsPYvzTEVyR8Tr0ekQ2kc+HvCJYRM5hlsJJoiiRkozHfoZZ7Gkem3S1C/w0R3ZTawJrGHbXVJQTH1ZQDU9734xoismj6rRmg9Mi++PFnNwtuLKZN4qxHjVW3yXAow65du6D1RpriJaWU9AK2q1OHwqVZj+TQ0Nx0hwsxlCrHa6Od1b7wAGzOktI1Bk8oweMHEo4K+0wVHFjWr98csH4J+NkX6iIlZ1ePGeJmUwyQXwiMggXxszZ0AtmFFa70BdNk/trsfII8tyKtXL5xNsCc/ZRng+fhKecprw67DLP/exMThu66FpDHdxxZx89vHEDER1CA30GlscbjJGG+eCOklA47/VfA4fZXNJL94roHbADeBp0OigDqlDiMdoBXF4DZrV0dAf8lG9HaKSpUqk0Ebnx/JvbNBYZruBx1xBpPBl6pRVHN6tLU3b1HfbIRyj9yxyzwE0CPRu8wvmEThybyOSZkSG6jCiKYy4XhR8mYrdNRBIrJiU3b31jR8EzD1wt5CJvnbhItj2PHOj81itypVr/46kpZZvcAhyzX6V3i46Yu+hfa5V85xyQq8ydEcH4sgEsarVSrAFFhr7DOMqCYM=
  - secure: a5xdbLlTqEI/GFDi3/JRoDq4jGqmsKf1ZTu9KDjiZZ/53AZ7ArY/uJksfdqmd58bLDukOEDuL/CdJQ5pkfVUNtXbR7lpBRUJCVV/4Ca+8hS+FFNyYpccN9VruI74NwYtx1mzB9W6qpmpSjO6dEhV2VpxCrKpFTNKYBJfqvnxiVW101cPy8KUegCAFVVExmwUx/E5XKvRVnfV8ue8qC0omY+s3Na6UcIK7O3AOMOjZb8OtaILpCWV9CfOzGq4+curpFVxowxJr8PrKn5+AsZkweiIFHT0QnC9RF4we33swGaPBVCD4tLpP5oJd+Yu5qBS7myBxE0zfhvxHwzCFcUItMeBaPim5kD/lFvUnDBrWXC88FErqe+yKtso75/FqqEuDJD1UK8wkGiXKqb7r52rRlEiWP1kHCSfWSnXWQRahmUnKCmeUm8Pve9aTnyFozjOIzlo6q29/0g7cqhP+/jf1WUWIkIxlt/7JNAPv0c7USHEE7WNb3sgvu4imnR+8jaExQcIUig04E9R2cLrJalDUEu6I8sdp6m7ZydaDvdSxkGo0OUWzmwC3HuZBJ3tnwx0E3KCtm/bbYP2Stz3uOLYszqA1nEACdzlVkjrTD0ztYx1R2eZ1rjGlOKEJiDi6mTkneHl45OpIib2wPNj9klzvWu6Bn5UKvRE1FhyoDSVnBs=
  - secure: RiRjdfwboZCyfWjVzZZhrimzZtfFEswDIeptOqFhU+F9FkfUNLCC17UaB1HtgiruTsT2c3XEwVTpNJQVtNw8VwH86PVNna0a4Ae2Um6IpylSW8P7UAvp3tHU/8JEWzf2kvlb2OL29Kq8aUCTuWwnbFncPwqHxzv0Hde9s/OzooOPA2HFQ/7hufCoRz/Aqoy3H9INiG84pWNBP5RxWEr6AphpZdmVZeJQFHRXVWii1p+lphQ9YgdjICMDHrDFeZo3TQDZ36RKCq78UefwAS4pvGdyRsdkDx7QAiBDNbx665PGiU6YEClyG5RAKJL9rX70hbUU45SbtAgSx9b9kuXX5hvfGvoHcVOCpjgFKKgCb9pjHIzCSQAMEeSN5wDsJSANfbviSb9ZtQWr3Rke2Zm1frdMZ2KQOf5F+ig9Lna5M2EzH86asNRqcXygQPMCYjaM3oBIe1vhYdB370AO/6gULse++zEaL69iF22m7bVYkgYgz+31adDz4Yd0HhPIWkFA21oaqr7W3fL6JOzfuqnjIaqu1Bon98tBH5MZZlOjZj+gFzWm4THwf6bmh3FeiBjNH/XjBJlXqR5d4afJkGUOU+I/vjSO/LTCO/+zPmpINz/a0azf+Iki+eUaMAl9wBEgyleq0WwV2CMXyv0KZENZ1HZX3XODIR4EESA3ZfgUVsg=
script:
- molecule create
- molecule converge
- molecule verify
after_script:
- molecule destroy
  before_install:
- openssl aes-256-cbc -K $encrypted_9b640e841e7c_key -iv $encrypted_9b640e841e7c_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- mv google_compute_engine /home/travis/.ssh/
- chmod 0600 /home/travis/.ssh/google_compute_engine
notifications:
  slack:
    secure: xlQ5NWrGWenFE5E7M9m9FIebcbo5Lg17gSGCftl135brltT9w05fvAdBKOPmE5uZxgcrUNxJeUl3MWLuwHVaXHJECqNWmSfTLQ7D/GvnDpxgXyL4kvQlri7lujXBaC2ticSs0NSPfQA3JTewj76mypZQq4bfGQ4anXfyhhH+mlPdUOSYoVitE/qnqryUIskgvSfC3M2AIOcmBSVJFoN6L28l4Ld9qIVfh7oV1OpqeUk62BUoLMuRq8OZWUqFqiTLD9KrmegJlqdx7Ixh4z0nJ96Zvr3x7/6DLtxTv6IfcyWIWi4xda7Ym5Am6RiaO45WyAX/sxt24imb+b1BHmP8fcIg0yN8LgI+iAFveGan4IvEDVzbp63muVnng7zbtPyWKaK4qAmBm5C/IavSNMTv6mIBjc9HAZgV42jUWLnzpHjgjGJT3JMUTzp2IPk4H6XlZPQ1tfwuwe9IUujydyWZgdsJmcYAeuqPE3kLXBeVFQrilE5/itd2m68w6bQ1Gw9u9Gfq9JAxlcT7SZ8UIzq9NI0cQSm3nGo3AfxIoBKpiVwl9uA483RdhzowejR7f9WbOkQbdUYb2XOy5rh3njt6C71MNADgLRmpaIsty4agFAp4FZ/gEGsVUYcVjdpLLXIO3gMdS34WEQZBdhWsP2ApVTV9n87Bakq1k4XV/7mKefY=
