language: python
python:
- '3.6'
install:
- pip install ansible==2.3.0 molecule apache-libcloud
env:
  matrix:
  - GCE_CREDENTIALS_FILE="$(pwd)/credentials.json"
  global:
  - secure: EaRAtXjm17SK2RuiW2DRZ6CxxN+OTEqsHn/+wd/L85VdHuQpVrLzaSa073SkvUXcYDphLY0f53lXgz4yuVncNNj3YrUJOKNVGuP9EpTnBfG5x1gbGdaci2CtXTtjmCLwkypDhJdyNH1fyTL+KcDDZUBLOB4qWYmR1qeTX8fWJMI54X0ivpbP6VtwO/xCT0RPXCEbjjdgOuEZh5AiLtXKmH5ZwI07ToTFVxVUGlIuMvw5kRPrLG79um8yxDXWz888FicRJ/RpK3B5fo3AMmp3jxupPN/ac/tVlJ8LasHAzbSfqEvLMhi1446T+t86pk7uOyheHy3U58iQ5L7rQI5WfF9OVEjebMJqHfYiL1JMwCwV1PlGpnI+zn0WTvLwGGIAFddadkstE2P+AiKeEuaBYPwXY1aLNtI94sFU7QNA+W5GtC0WOys4mf8uFl+JF+0YDG64YILIqcRgKkoWY9QSp05g0olwxKzW4y9IMt1JmE68CZSi6rNS5usO/zFT+voL++FWrDNpX7nrDF03hJrRAWwEOtkLY/u+j6WZo9GXHf7F5ORuL6GfmX1cKNk6DK56v/2qRWt1lSMZvCd38Bt0bkKr3fQdb+yN98aup2ByRUQaYaLiKR3b151tSC/MdZBBjhKSAOcszYSxEJf8t9AEIWtRVDsXH56v33vasyVzH4Q=
  - secure: PYgwGMNzmaz/s7UV7p6LhE2BSEVT/KQz9c1pZLRVTAtW0dD0s6/YsJmN2YgNJ2sMJ2rQdd4bTZEp0GROfoAe+VBa8v9ukVU8zsHLkBoQdntDTa1e+aXLbT6LhIWWMIyghQcARvfe0p6ft0utu589mqGmoy7ZwefQO+tD/n33962q8sJjsiynvnPuPzVYOigdrr97MB9P138t1Ke6t0QaDC6KWDPzxhxC4dX+ogMAoMCP3YH+d8+Xq+K/JHUUlBTyL5gGk1sHBxr2R0zBC6uzKZP81z+OIIIpZXJURnp2xoZkd1fGqfhl4YYUphapIWq0o87X1FK2/plOpfzxrVrv73E5yDw9CPv0OgeeGc9I671HXabvRrFSVHZMmqhHl5D3zVHfooCUF6GjXYjqMdbbbi2rG1IEugVlxvpfUUevFoW1rdXlIPDQjNwVlQcySxEmEO8hxx8AGnOBx4+VDNhD6ShrdMqKm7J+PImf4psYyjM1jW0ZZe8xiXEo/JaG/JA5aYj++0KJz2FsXg/fhnexX9Wz186cYhYsDDTHu0AdgWwRdzBQTPL1+JdatnRLU2yrjrSY3zIKAToFNYH3AJ0oPZfKMKj8ugajMTJ6OhcUcz/qjlsawQr+rB5KyYdCiN5Bwpa5b6dwF2W7lsaU5FCvX+6SB6SX70yv9wgD3DdkB8w=
  - secure: CO4AjNeVVf9hiFN+JPyTyBzP0JuS0VR6mdt27gkbX15wEXaVMurDVS+tj0Uar692FLJ1iw8vMORbWzfQjOj1Jh6+RL3eiYv5T0m1rHSsQh25aWADDCdkz4cl3T56fIANw1i6WngglmiY/+y3dpSAl4ua5VOAXyuWFsLFn4tTXJS+8eC4h2b5LkVHM+sOj1eHPRQ7tZnpYNM+b+7Y5/ocEGkh0kS0uUheY+dwHH585kNaP+TsZxrcNETutZCyy9+fOrnMSgM64X35P6bb8zyQCd3evGDe2ANwAXgCGQegy6zqkvRJVNPkzGRnngWKu9os93gw14eLwYKkSS2TV1QZ93EqC1n+OHTK14jCQGup+3c6PZwW5/o61TXVeFuDXbL+Jm1uSs/U6Fm2QQxpnGJPPaFjJWs4Ll7wq+B58g/nBLmr/CY3d0yUX+DmVEHw2gDROWyXOwADKoCdgRxgZfM6HX+uXt0L6cyI+a2CHa2j++2ao2y/I3myxeOPJQDmpRqLL+CxFw+hJhDYFLCAQqNNNHLFXuQWfjDmC1KJERl6Qw3y3Y1G/h0Smdrq+/HRpCOH/tZ5EQPquVCghqiCVH/P0l0wsr77mF9zq4oSfeosmA27ISxgIQf93XnJlyjA+/fAwaDdrRW9p9WEjiH2uRCMKvcb+TosxhfLw18EfBXm3mE=
script:
- molecule create
- molecule converge
- molecule verify
after_script:
- molecule destroy
before_install:
- openssl aes-256-cbc -K $encrypted_9b640e841e7c_key -iv $encrypted_9b640e841e7c_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- mv google_compute_engine /home/travis/.ssh/
- chmod 0600 /home/travis/.ssh/google_compute_engine
notifications:
  slack:
    secure: xlQ5NWrGWenFE5E7M9m9FIebcbo5Lg17gSGCftl135brltT9w05fvAdBKOPmE5uZxgcrUNxJeUl3MWLuwHVaXHJECqNWmSfTLQ7D/GvnDpxgXyL4kvQlri7lujXBaC2ticSs0NSPfQA3JTewj76mypZQq4bfGQ4anXfyhhH+mlPdUOSYoVitE/qnqryUIskgvSfC3M2AIOcmBSVJFoN6L28l4Ld9qIVfh7oV1OpqeUk62BUoLMuRq8OZWUqFqiTLD9KrmegJlqdx7Ixh4z0nJ96Zvr3x7/6DLtxTv6IfcyWIWi4xda7Ym5Am6RiaO45WyAX/sxt24imb+b1BHmP8fcIg0yN8LgI+iAFveGan4IvEDVzbp63muVnng7zbtPyWKaK4qAmBm5C/IavSNMTv6mIBjc9HAZgV42jUWLnzpHjgjGJT3JMUTzp2IPk4H6XlZPQ1tfwuwe9IUujydyWZgdsJmcYAeuqPE3kLXBeVFQrilE5/itd2m68w6bQ1Gw9u9Gfq9JAxlcT7SZ8UIzq9NI0cQSm3nGo3AfxIoBKpiVwl9uA483RdhzowejR7f9WbOkQbdUYb2XOy5rh3njt6C71MNADgLRmpaIsty4agFAp4FZ/gEGsVUYcVjdpLLXIO3gMdS34WEQZBdhWsP2ApVTV9n87Bakq1k4XV/7mKefY=
