language: python
python:
- '3.6'
install:
- pip install ansible==2.3.0 molecule apache-libcloud
env:
  matrix:
  - GCE_CREDENTIALS_FILE="$(pwd)/credentials.json"
  global:
  - secure: k50sOQkUlhFAIaMlzRv73Ad6F6zGVtfSmwHVQ+2wvuQGl22QbPERoNMVnV2Jm8GBMYIDz7HJ/si4WJCvzf7mJD/xi/oZPm77KxCxF9K0uULaknN7pMivh1l5xxpM5a6auErINp4brTIo1kS9a3VLMJ8535tYtqkmOFysWnTqCwUcPqF4+wLERksiQpPBkZEKTwGTh+ImtQZ97dQzfkysd2RqzMowZ/oqTlMvGBa4pyMu8EtlmcvssvgxcqlcFQ+yxvxxGbu4u15+f4ou1A0FfePftTs1phAf5kcAl9Nx1O8FR3coaGn3HjDe633gveYFf+rCf6Beuo4p1UZ9nmv3tHLHfidpim7nkyNVnbGidD5+TXAK++Cx1SE//Sx3lEpIDBHqtt5Msd0ghAYwoMwjL0+pnn/gMHII/vf6pM0OXHguulqaKNl9SPGVEIb75L8WLFDbWs5fZIE5QQ39DRAuuCU82vDVsJIXuCly89ASrbwNEJRUtgPfhmg//Pe2ZFMInzGLs9Vu8X2ksoJMdcylCH8veS6KK0LCYyjcBaRVn65Issp3bcVSdwpt25LfRqpCKvDjSFyO9I4h1TCbn0mJyzbqKZVdK2g+T2BYJ7Z2GEpPKUipH08GUEFJbIJZT/njcRj5jdcnJkdlm7Da0WKZOv5DzW0FVJdLJj8zhjGHHis=
  - secure: d+G2GaKhX/woJNjORgQnsUqyMV7/nrPFvoBhA+g7JuHCl1fJLbZ69qgkkXMzjVnVQOGhCZ9hqDUc29n7mcDqENifOY5gsWFYB4SE7ZrjbXH+gy8rJZcmLtQenQcYu8W0+7UC8Vi1ULyncof5loF9gjYnrOuVz+rbbstuBD1CI5uJ9EWXYm71LIkjJ1ktV+hEtILtJqXwv12AQlwVcn8/C6nv/sEnHpDJCe4njyCtkXjNfNiPLDB5+ST4dSMCmvR0/opjdlFZMYfNMzsSDw2p83QmAffTIGJpWS3/xDxbmniCEuB/GSuUghMY3gUDAyB2i4Pt0Q4xp1tZqtZrtoOxAZLMKE4kM4PBDwcS6zNWuI2ToQHYfuRmvuoZDxDvBZF/ZTL7aCmaxisVjzWcGXN5zBTFzHpztuHJf8VSjz5kHpotY7xXFutRoaE34pHXCMFqmYoQgbJy6ky930QaqEAlkRwEKDQ1Xeq3gt9Zs4x+JpFeV1la8OZi4+cda1CaIgn/okAS2rAtE6NO7DTKTg3wZOc9bYhyVfC15M1jdCBXplRf+KLgOhqfdKYkykqWEwH5r42g1idjsrkUWJS9VnZfwvofnwvy9RLOZuMI8mlxrb+qZo/gbU/T/VoeBHMLBOD1fs/Jx/pL7WsbZSO0k8XUpXtETuPn4XeDFEuzVP2bDho=
  - secure: JpgdTo/ZkVOC0A65DJljfFsyQym7Ljy+pUew59sgydtBUXRWpbC7yIKYCgi6TZD4BYVr11okQOurX/L83+CJlYvTw/P4IMLB7VjYPlZ4RXk18RLjePGUUZjohSnWLOelyjyOgkbCq8xqmahq8Av7qFT5K+ua3PcZov8QBiNqlVu2+GoGDSUulMlK0b/jt9SKyb4Zkiq4zoOE4kulbUPh6uKyP7a32cVVo1LjUYrbtJYotfzlJRcrWiJ7RjWlE3yUlpsSHOpqE7KiJ34lO5mXDzSsMAguziGqHFI5YNtJXp0bVL1bYK5kh5MUIHLOtxPH+2WlqbkIhAvt5ZnmvIPHYaMdSYWDGD6jjVbrXKipoguI5S6Honzddt5E2Qo3dRIdMFnYq5JsKbgv2Z9Wn8LubwvVmoPUsiPRc9SZYxhnFTWKF5sW8t3NlkEjcq1z2MZF9Cn9O2Em6Fm6Jjd0aN78GL1bw6pjlOhkElc3we04m8pu1iE2jiGJKRnoKG94xvzojVQmr5HQcuD9Xa4iffj6uhXhy0OHKF+47vB3k+6bZ9Ktt7NhAaeYJwbQYLxMJu98zbtTikFfSEfG4jiHpiy6+nufeyqSnj4BOd2NfXG6kdNfXtkXg7TkFqJyLj/tqTSG4UeznYSo9Kms6PcUeFj0zXnBGGIIoxwG3flv0n3VRqI=
script:
- molecule create
- molecule converge
- molecule verify
after_script:
- molecule destroy
before_install:
- openssl aes-256-cbc -K $encrypted_6f208f95ce6f_key -iv $encrypted_6f208f95ce6f_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- mv google_compute_engine /home/travis/.ssh/
- chmod 0600 /home/travis/.ssh/google_compute_engine
notifications:
  slack:
    secure: xlQ5NWrGWenFE5E7M9m9FIebcbo5Lg17gSGCftl135brltT9w05fvAdBKOPmE5uZxgcrUNxJeUl3MWLuwHVaXHJECqNWmSfTLQ7D/GvnDpxgXyL4kvQlri7lujXBaC2ticSs0NSPfQA3JTewj76mypZQq4bfGQ4anXfyhhH+mlPdUOSYoVitE/qnqryUIskgvSfC3M2AIOcmBSVJFoN6L28l4Ld9qIVfh7oV1OpqeUk62BUoLMuRq8OZWUqFqiTLD9KrmegJlqdx7Ixh4z0nJ96Zvr3x7/6DLtxTv6IfcyWIWi4xda7Ym5Am6RiaO45WyAX/sxt24imb+b1BHmP8fcIg0yN8LgI+iAFveGan4IvEDVzbp63muVnng7zbtPyWKaK4qAmBm5C/IavSNMTv6mIBjc9HAZgV42jUWLnzpHjgjGJT3JMUTzp2IPk4H6XlZPQ1tfwuwe9IUujydyWZgdsJmcYAeuqPE3kLXBeVFQrilE5/itd2m68w6bQ1Gw9u9Gfq9JAxlcT7SZ8UIzq9NI0cQSm3nGo3AfxIoBKpiVwl9uA483RdhzowejR7f9WbOkQbdUYb2XOy5rh3njt6C71MNADgLRmpaIsty4agFAp4FZ/gEGsVUYcVjdpLLXIO3gMdS34WEQZBdhWsP2ApVTV9n87Bakq1k4XV/7mKefY=
