language: python
python:
- '3.6'
install:
- pip install ansible==2.3.0 molecule apache-libcloud
env:
  matrix:
  - GCE_CREDENTIALS_FILE="$(pwd)/credentials.json"
  global:
  - secure: ucBrM8jQ9K6vePkvqP4o+RIXxCf8TxJujB7v4JYx/XFwXWmDN4OSZn5QSmOFaSvW+UgSo1f/yQOYULFa4qGhd9ykazv04r5reQujNk8ZEDk23YsNvazLpzitwinFrMHVJRExF8snyJp2VM0jn46351x3KC6tA8+tV1tK+mghS3HgJUM524TeT8Jja/gnhG+lf/DD8zXH5XqXtzFJWzSI53+FijPUDeApGzclcjWVdP/HWmBLtneFq8as0+TTWKOz2oXgX+fpSkyxWrKx+3i/CEQ89EVX8IaXiRqVaZZ1EoHZmzGgdyzuZzQKt4ri3k9DGvFof1kz3wNSjfFioUM28n0VQ1FpSsG+1i33lA2sbmC5udjqitxVTL0ACDv9htB78WFfWmvvX+z1SjJgSq5oXqMzp1LAJj8BiLYtjCULZXrb+j9sPiBhVmxrabnsa/O90q72dozuFyeR+yYdSdLGyefz+2kj+qaSG/hNVWOsdg+a6MKSB7+eqwwc6HQ6KHUUrir8J7PLALxtK4xJe0P3aBAszf+P+iRNa0kSd1r+Awr1rbPPXQOVTNED9hHVOslqryUsS65NjG725MxTcm6VMbrV73QFlgzopZnhK9mQFyv6vxH8kztgYARXOxQnyqiBRuFjDH1WRZbEPPoR7vayxmtZpfi1l9aAvm9Ka7P4xio=
  - secure: aA8v5QJETRPjrWhk36fjlo3sYSWU1VKW6dnn429N3+QCGKvBvQhV4101/YPL5Dbw15Qtl+L5iFLehM5PV5At5l7J4GaAQT0+R3+AEp7VJ9WL6X8Ae7qstjvyPFVfng1AH3u/NpOeNlfi4hboFpD2cIU28nOZHGBtUxXVMyHTZzIEcTbseSm9PYgh9m4kSRPPHNGWr7DQuGvX37CMolyTl3UOFmOFSAlDO17finLsvHZ3RVBOYWoXrUIpTJkUXupO2P+TZJC2urBCpbZo7+/dMipeUsIsID36q5aco9nGBCc8ebYFj2g9frp7vK88COFj2Ms37rYCZe8wNH6IVWy9NZR3qrj8IseZIdRi1dCDNmx4/fZxmn/oXZrUkqfTZwk+PhE15TnY6SkRVC74Gy2ph17kLi30RUrL7VTVi5xY1NqvPN4hPkl1Z9ilt6XYoOEj6UYmnxa9aZPSK+lj+t0Y0KsJ2gtb87LbPY5oOc1tJ8yY3RomKYrWjAX7am+5nn3pKkjzKNTAmXosRsb38EclKcfhETMD3NsxzWrROZCsO9z1h+po4CPZB/aE+E5fkE9sdKil+1B3iCUg/gzLcr2q66YsrgUkw84nj3JIDh9gm9okih6yFaeK6USz2l6toiJfwJwb7Bs9mAuHJMYLMqFnvGBX89OoF67lTitAHyrYjuo=
  - secure: AcuNZtlrMTgWjHB3nX5voi405vtesen2UwUJ4PXqYHH4wwI6da/UNtkvOf48h32vb7flhkZyFE/CZinn+Z8kk/0nBmRxjlCLcqURrz63IQBWAaP1IEsPHzopYmwcpxCbOtYCgw3CjkQaoU24erSSsk9jUFMm1XWULenlTRrowdD1YPqK0WwhI3lQL7fiFiWxAgB/6ZNr+LK/0dfezY1eXt7Wk51ZhAVNiivOTx/b5Z0/Y8bEQFA33wXBNQK2l46dpGZcSILcE1JYcsO7SiryEmLkwa87aYhiHGJZeAAB9Mz7dwbMloGUw3BBRb+/Jfr2sWZXbqRPVMY9exmzcqtKylbRKw27Qa5yH9bgZ9tmevS8zFhrQ+eznY2CubiQl0zIjRzt5nslF0i6kak/lsFMyCxNEYlBE918f0wK5NKL7YLCkcONUxdfVJPtQIaTXSwhSg4O0ws8em/XxwtFhpfW99YCTcw1Coi3vLrjaRoOoH5aZGh/ygCx1+Yr6jUC9wuCn69m6RzHB8jigH+c4Z4Wes2wMkdoDvoMx+oo0J6R07IPhcl+E9DfZ4SglzlniXx7e48SyKsP0YhQ/fVtWulIIRYN/iNLL9YE3R4XHT7uuQwMwm5kKoElfepX4ob2/4Vc3eEOiD0Q7kUJfp89pr0floJHXRl+1Q8hkeoNihFhGz4=
script:
- molecule create
- molecule converge
- molecule verify
after_script:
- molecule destroy
before_install:
- openssl aes-256-cbc -K $encrypted_6f208f95ce6f_key -iv $encrypted_6f208f95ce6f_iv
  -in secrets.tar.enc -out secrets.tar -d
- openssl aes-256-cbc -K $encrypted_9b640e841e7c_key -iv $encrypted_9b640e841e7c_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- mv google_compute_engine /home/travis/.ssh/
- chmod 0600 /home/travis/.ssh/google_compute_engine
notifications:
  slack:
    secure: xlQ5NWrGWenFE5E7M9m9FIebcbo5Lg17gSGCftl135brltT9w05fvAdBKOPmE5uZxgcrUNxJeUl3MWLuwHVaXHJECqNWmSfTLQ7D/GvnDpxgXyL4kvQlri7lujXBaC2ticSs0NSPfQA3JTewj76mypZQq4bfGQ4anXfyhhH+mlPdUOSYoVitE/qnqryUIskgvSfC3M2AIOcmBSVJFoN6L28l4Ld9qIVfh7oV1OpqeUk62BUoLMuRq8OZWUqFqiTLD9KrmegJlqdx7Ixh4z0nJ96Zvr3x7/6DLtxTv6IfcyWIWi4xda7Ym5Am6RiaO45WyAX/sxt24imb+b1BHmP8fcIg0yN8LgI+iAFveGan4IvEDVzbp63muVnng7zbtPyWKaK4qAmBm5C/IavSNMTv6mIBjc9HAZgV42jUWLnzpHjgjGJT3JMUTzp2IPk4H6XlZPQ1tfwuwe9IUujydyWZgdsJmcYAeuqPE3kLXBeVFQrilE5/itd2m68w6bQ1Gw9u9Gfq9JAxlcT7SZ8UIzq9NI0cQSm3nGo3AfxIoBKpiVwl9uA483RdhzowejR7f9WbOkQbdUYb2XOy5rh3njt6C71MNADgLRmpaIsty4agFAp4FZ/gEGsVUYcVjdpLLXIO3gMdS34WEQZBdhWsP2ApVTV9n87Bakq1k4XV/7mKefY=
